### ISSUE TITLE
Frontend dev build got deployed & published

### ISSUE THREAD

**Issue by jessuni** [weidian-inc/weidian-tech-blog#17]
借地打扰了……
你们的前端工程师把 dev build 发到线上了。而且前端的 authentication 校验是在 router 的 after hooks 里触发的，也就是说会先跳到登录后页面再跳转回来。
![image](https://user-images.githubusercontent.com/41285428/108597568-02f48000-73cd-11eb-8d61-122aa957d480.png)

地址 https://d.weidian.com/

**Comment by junjie-xyz** [comment]
@hoperyy 叫洋哥看看，hhh

**Comment by hoperyy** [comment]
感谢反馈，我转给负责的同学看下 @jessuni @IOriens

**Comment by liu0418sky** [comment]
能加一下我的微信吗，ly939149724，和您详细沟通一下
